Page({
  data: {
    "name":'某某某',
    "Urg":"非常紧急",
    "orderNum":'201906181200000103757',
    "orderClass":"科技公司技术部",
    "orderType":"采购申请",
    "payTime":"2019-6-30",
    "payMon":"3000",
    "payDes":"CSS 为定位和浮动提供了一些属性，利用这些属性，可以建立列式布局，将布局的一部分与另一部分重叠，还可以完成多的任务。",
    "payObj":"某某某",
    "payType":"收据",
    "payClass":"支付宝",
    "payAcc":"13301320123",
    "payRem":"CSS 为定位和浮动提供了一些属性，利用这些属性，可以建立列式布局，将布局的一部分与另一部分重叠，还可以完成多年来通常需要使用多个表格才能完成的任务。",
    "apprExam":[
      {post:"发起申请",name:"某某某",time:"2019-6-12 14:21"},
      {post:"审批人",name:"某某某（审批中）",time:"2019-6-12 14:21"},
    ],
    "srcs":[
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
      {src:"/image/head.jpg"},
    ],
    "navIndex":'0',
     progess:[
        {name:"某某某",pos:"申请人",pro:"某某某"},
        {name:"站长",pos:"站长",pro:"审批中"},
        {name:"人事",pos:"人事",pro:"某某某"},
        {name:"财务",pos:"财务",pro:"某某某"},
        {name:"总经办",pos:"总经办",pro:"某某某"}
      ],
      CC:[
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
        {name:"某某某"},
      ]
  },
  onLoad() {},
});
